### ISSUE TITLE
ISSUE: OpenAI API connection error with llama_file in embeddings.ipynb

### ISSUE THREAD

**Issue by cstonk89** [alfredodeza/learn-retrieval-augmented-generation#1]
When trying to reproduce the embeddings.ipynb, I am getting a connection error when attempting to connect to localhost address (http://127.0.0.1:8080/v1) via the OpenAI client suggested in the notebook and README. My machine is a MAC running an M2 chip, my venv is generated and managed through poetry and I'm using the TinyLlama-1.1B llamafile model if any of that helps.

**Comment by alfredodeza** [comment]
Have you tried using something like this:

```python
from openai import OpenAI
client = OpenAI(
    base_url="http://localhost:8080/v1", # "http://<Your api-server IP>:port"
    api_key = "sk-no-key-required"
)
```

What HTTP error are you getting in the error? Can you request that URL address with `curl`? Can you help me understand what is going on by providing me more context as to how you are running all of these components?
